#!/usr/bin/env python3
"""Generate exact canonical color tokens offline; --check rejects source/table drift."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
COMMIT = '1cc4e6667aa86444a7e9055549aa85cac293dc07'
FAMILIES = ('azure', 'mist-blue', 'sage', 'stone-teal', 'dusty-violet', 'warm-sand', 'olive-paper')
TOKENS = ('--ink', '--muted', '--faint', '--grid', '--paper', '--panel', '--line',
          '--accent', '--accent-ink', '--accent-soft', '--edge', '--group', '--group-line',
          *(f'--s{i}' for i in range(1, 9)), '--pos', '--warn', '--neg')


def generate():
    raw = (ROOT / 'assets/canonical/theme.json').read_bytes()
    source = json.loads((ROOT / 'assets/canonical/source.json').read_text())
    if (source['repository'], source['commit'], source['path']) != ('junix/diagram-theme-rs', COMMIT, 'registry/theme.json'):
        raise ValueError('unexpected canonical registry source')
    if hashlib.sha256(raw).hexdigest() != source['sha256']:
        raise ValueError('canonical registry SHA-256 mismatch')
    if hashlib.sha1(b'blob ' + str(len(raw)).encode() + b'\0' + raw).hexdigest() != source['git_blob_sha1']:
        raise ValueError('canonical registry Git blob mismatch')
    registry = json.loads(raw)
    if (registry['spec'], registry['version']) != ('diagram-theme/v1', '1.0.0'):
        raise ValueError('unexpected canonical registry schema/version')
    if tuple(registry['themes']) != FAMILIES:
        raise ValueError('unexpected canonical family names/order')
    variants = [(family + suffix, registry['themes'][family][mode])
                for family in FAMILIES for mode, suffix in (('light', ''), ('dark', '-dark'))]
    for name, tokens in variants:
        if tuple(tokens) != TOKENS or not all(re.fullmatch(r'#[0-9A-F]{6}', color) for color in tokens.values()):
            raise ValueError(f'{name}: unexpected token names, order, or colors')
    lines = ['// Generated by tools/gen-canonical-themes.py; DO NOT EDIT.',
             '// Source: https://github.com/junix/diagram-theme-rs/blob/' + COMMIT + '/registry/theme.json',
             '// Registry SHA-256: ' + source['sha256'], '',
             'export const canonicalThemeData = ' + json.dumps(dict(variants), indent=2) + ' as const;', '']
    return '\n'.join(lines).encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ROOT / 'src/style/canonical-generated.ts'
    expected = generate()
    if args.check:
        if not output.exists() or output.read_bytes() != expected:
            parser.exit(1, 'canonical theme tables are stale; run python3 tools/gen-canonical-themes.py\n')
        print('canonical theme tables match the pinned registry')
    else:
        output.write_bytes(expected)


if __name__ == '__main__':
    main()
